### ISSUE TITLE
Not Working in Proxmox

### ISSUE THREAD

**Issue by MichelDiz** [blend-os/blendOS#1]
I have downloaded via Proxmox download tool and gave me "Access denied". I tried again to download in my machine and send it via NFS. Again the same error. Looks like the UEFI or the BIOS(I tested both) can't be able to find the boot sector.

In general when this error "Access denied" happens is due to incompatible Bios. So I have to change from UEFI to legacy. And works. In the case of BlendOS I had no luck.

Here is my conf file
```bash
root@pve:~# cat /etc/pve/nodes/pve/qemu-server/406.conf
boot: order=sata0;scsi0;net0
cores: 8
efidisk0: localdisk:406/vm-406-disk-1.qcow2,efitype=4m,pre-enrolled-keys=1,size=528K
machine: q35
memory: 11048
meta: creation-qemu=7.1.0,ctime=1674785339
name: blendOS
net0: virtio=D6:D7:20:46:92:CA,bridge=vmbr0,firewall=1
ostype: l26
sata0: localdisk:iso/blendOS-2023.01.26-x86_64.iso,media=cdrom,size=1453676K
scsi0: localdisk:106/vm-106-disk-2.qcow2,iothread=1,size=132G
scsihw: virtio-scsi-single
smbios1: uuid=///erased
sockets: 1
vmgenid: ///erased
vmstatestorage: localdisk
```

PS. But I have booted with Ubuntu and I'm able to access the CD-ROM and see all files in there...

**Comment by DanielTolentino** [comment]
Can't boot the ISO on VirtualBox and VMWare too.
I can mount the image and see the content, but it doesn't seems to bem bootable here.

**Comment by robinemery76** [comment]
Not working as a bootable medium in VirtualBox.

**Comment by DeVelox** [comment]
I was able to boot it in qemu with UEFI, didn't work with BIOS.

**Comment by MichelDiz** [comment]
@DeVelox can you share the arguments?

**Comment by DeVelox** [comment]
Just added a simple `-bios /path/to/OVMF.fd`, nothing special.

For completeness here's the full command that I'm using, but note that I'm using this on Windows atm:
```
qemu-system-x86_64 -bios ..\OVMF.fd -accel whpx,kernel-irqchip=off -machine q35 -cpu EPYC-Rome,-monitor -m 4g -smp 4 -vga virtio -usb -device usb-tablet -audio dsound,model=hda ^
-object iothread,id=io1 ^
-device virtio-blk-pci,drive=disk0,iothread=io1 ^
-drive if=none,discard=unmap,id=disk0,aio=threads,format=qcow2,file=disk.qcow2 -cdrom %1
```

I also did a quick livecd test in WSL2 Ubuntu:
```
qemu-system-x86_64 -bios /usr/share/ovmf/OVMF.fd -accel kvm -machine q35 -cpu host -m 4g -smp 4 -vga virtio -usb -device usb-tablet -cdrom blendOS-2023.01.26-x86_64.iso
```

**Comment by RudraSwat** [comment]
> Can't boot the ISO on VirtualBox and VMWare too.

You need to enable EFI boot support, as the current ISO only supports UEFI systems at the moment (since it uses `systemd-boot`; we'll be switching over to GRUB for the ISOs in future).

**Comment by MichelDiz** [comment]
@RudraSwat that's the point. My first attempt was UEFI boot.
I'll analise DeVelox's comment and see if I can reproduce in Proxmox.
