### ISSUE TITLE
BlendOS install stays stuck at 8%

### ISSUE THREAD

**Issue by Githubguy132010** [blend-os/blendOS#125]
When I install BlendOS, the installer stays stuck at 8% and the installer says the install was succesfull but clearly it is not. What do I do?

**Comment by Ast3risk-ops** [comment]
So after reboot your system was broken?

**Comment by Githubguy132010** [comment]
Yep, but I already fixed the issue.
I reformatted the usb with Ventoy, copied a Debian ISO over and installed
it. From there I copied Pop!_OS over to the usb stick and installed
Pop!_OS. So I have a working system now.

Op di 26 mrt. 2024 19:04 schreef Asterisk ***@***.***>:

**Comment by Ast3risk-ops** [comment]
Then close the issue (you can't do that over email)
