### ISSUE TITLE
I want to install another Command Line emulator [Alacritty], how can I install it natively (not from a container)?

### ISSUE THREAD

**Issue by pragmaticmero** [blend-os/blendOS#14]
The problem with installing Alacritty with a container, is the lsblk command, it doesn't work as expected. it gives me a completely different directory address than the native "Console" application for the disks, and I don't know if I can edit native files from the terminal using neovim, thats a phew reasons why I need to install applications natively. 

My expectation after seeing the OS's web page was that this distros could install packages natively with pacman, and enable/disable the immutable mode with a command like in SteamOS or VanillaOS, not that everything will be inside a container all the times..... Its a dealbreaker for me, how can I install a couple of applications natively?

PD: Also, I can't execute commands like "flatpak" inside the container to install apps on the main OS, because its just a container Lol, is its own distro basically, so no running commands from alacritty to manage my main os, basically this distro removes any kind of choice that you can make about it.

**Comment by RudraSwat** [comment]
```
My expectation after seeing the OS's web page was that this distros could install packages natively with pacman, and enable/disable the immutable mode with a command like in SteamOS or VanillaOS, not that everything will be inside a container all the times..... Its a dealbreaker for me, how can I install a couple of applications natively?
```

You can do that, run `sudo nearly enter rw` to temporarily disable immutability, run `PATH=/usr/bin pacman -S [PACKAGES]`, and then enable immutability again with `sudo nearly enter ro`.

**Comment by pragmaticmero** [comment]
Thanks Rudra, sorry for being rude haha, I love ur os, it's amazing. Keep up the good work, closing issue cuz working.
PD: Also I can't see any specific documentation in ur github nor in the official webpage, only for the command blend in the github of the project. Is an official documentation planned? If so, can the community participate on it?

**Comment by aksharlabs** [comment]
> ```
> My expectation after seeing the OS's web page was that this distros could install packages natively with pacman, and enable/disable the immutable mode with a command like in SteamOS or VanillaOS, not that everything will be inside a container all the times..... Its a dealbreaker for me, how can I install a couple of applications natively?
> ```
> 
> You can do that, run `sudo nearly enter rw` to temporarily disable immutability, run `PATH=/usr/bin pacman -S [PACKAGES]`, and then enable immutability again with `sudo nearly enter ro`.

Nearly command not found
