### ISSUE TITLE
Minimal install?

### ISSUE THREAD

**Issue by tarneaux** [blend-os/blendOS#18]
It would be great to have a way to install no desktop, no plymouth, no fonts etc. to just have a xorg to start with and install own apps and all, because I think this distro will be seen as "bloated" by many people (me too). 2.5 gigs of pacstrap is a lot.
Of course that would be keeping the purpose of blendOS, like the immutability, distrobox etc.

**Comment by Moutasim02** [comment]
I think the distro is serving a purpose. and that will obviously increase its size, if you want a minimal distro I would suggest staying with Arch.

**Comment by tarneaux** [comment]
Actually I quite agree with that. Having all the package manager tooling, frontends and so on would still make for something large, even without GNOME. Having multiple package managers in of itself doesn't fit the philosophy of extreme minimalism that comes with AL. Closing.
