### ISSUE TITLE
support for arm64/aarch64 ( raspberry pi 4b)

### ISSUE THREAD

**Issue by AmirulAndalib** [blend-os/blendOS#2]
hi, is it possible that you can add support for arm64/aarch64 architectures embedded devices eg : raspberry pi 4b ? if so it would be helpful.

thank you

**Comment by albinkc** [comment]
would also help it run in a VM (parallels, VMWare, etc.) on Apple Silicon Macs

**Comment by RudraSwat** [comment]
> hi, is it possible that you can add support for arm64/aarch64 architectures embedded devices eg : raspberry pi 4b ? if so it would be helpful.

I'll be adding support for aarch64 and Raspberry Pis in future.

> +1 would also help it run in a VM (parallels, VMWare, etc.) on Apple Silicon Macs

You could also use UTM on M1 Macs to run the current blendOS amd64 ISO in a VM.
