### ISSUE TITLE
Can't boot into BlendOS USB on HP laptop

### ISSUE THREAD

**Issue by Jrdnkasparek** [blend-os/blendOS#30]
- HP laptop set to UEFI won't boot from USB
- Tried opening to EFI file, still won't boot
- Secure boot causes error with invalid signatures

Will only show screen below

![Fn6YnjfXoAAS_HB](https://user-images.githubusercontent.com/20908630/216504146-5b6de795-0813-49f2-b5a2-13260041e75e.jpg)

**Comment by Jrdnkasparek** [comment]
![Fn6dwweX0AA8pT7](https://user-images.githubusercontent.com/20908630/216504256-0e5ce22e-baae-4884-8cc5-234d7084219e.jpg)

**Comment by Jrdnkasparek** [comment]
![Fn6dwweX0AA8pT7](https://user-images.githubusercontent.com/20908630/216504555-8721436f-e984-4c22-9527-b6f23d1e1b43.jpg)

**Comment by johanesPao** [comment]
Perhaps you're using Hybrid ISO mode when you flash the ISO to USB (using Rufus perhaps?). Try using DD Mode instead.

I experience the same problem as you are on Hybrid ISO mode, works well with DD Mode.

**Comment by Jrdnkasparek** [comment]
> Perhaps you're using Hybrid ISO mode when you flash the ISO to USB (using Rufus perhaps?). Try using DD Mode instead.
> 
> I experience the same problem as you are on Hybrid ISO mode, works well with DD Mode.

That fixed it! Thank you! I always though Hybrid ISO was a mix of both/better but alright
