### ISSUE TITLE
Ability to install in a similar manner to the arch linux way

### ISSUE THREAD

**Issue by MichaelPetersen22** [blend-os/blendOS#38]
Wondering if it'd be possible to add the ability to be able to install this in a similar method to how arch linux can be. Allowing for the user to have more ability to customize (i.e. an encrypted btrfs file system with custom subvols etc.) Using a specified bootloader etc. But also just maintain the ability to use the blend functionality / have access to all the package managers.

**Comment by GrandMoff100** [comment]
Well, that might contradict the philosophy of running multiple isolated OSes. Depending on how they store persistent OS sessions we may or may not actually want to customize blendOS itself like you can with arch but you could probably customize each guest OS. Although this kind of control would be cool though.

**Comment by MichaelPetersen22** [comment]
Alternatively to installing it the "Arch Linux" way would be to have the option for the user to just have a terminal environment? Or select "No Desktop" when prompted for a Desktop Environment option in the installer.
