### ISSUE TITLE
No bootable media found

### ISSUE THREAD

**Issue by Xdavius** [blend-os/blendOS#39]
Hi,

I've got the same problem on both VMware and Virtualbox. I suppose the iso to be broken.

**Comment by Dhillon-16** [comment]
same here

**Comment by Xdavius** [comment]
> Read up review on Distrowatch. Learnt i need to setup the virtual machine in UEFI mode. After that it boots up. Am now in the process of installing. Am using KVM and VirtualMachine in Debian Stable.

Yes. EFI is OK. Now I'have an other problem ! thanks
