### ISSUE TITLE
Installer stuck on select locale

### ISSUE THREAD

**Issue by lol90101** [blend-os/blendOS#56]
The next button is grayed out

**Comment by lol90101** [comment]
Incase of a hardware specific issue somehow I am using acer aspire E5-575T

**Comment by lol90101** [comment]
I switched the locale and it fixed, pretend this never existed

**Comment by mkauzlar** [comment]
I have the same issue and I'm unable to switch locale

**Comment by lol90101** [comment]
To change locale, in the locale menu click the add locale button, check the set as main locale thing, and click on that locale, and you changed the main locale successfully in the installer
