### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rockierock** [blend-os/blendOS#6]
Can you put on some sort of installation guide!!

**Comment by Samia-47** [comment]
booting screen just keep circuling and not proceeding further

**Comment by rockierock** [comment]
It's the same to me

**Comment by rockierock** [comment]
It's just the same with Mee too 
Literally tried to do every possible way to install it. Still no use

**Comment by XxnittanixX** [comment]
doesnt even show up for me it just says invalid file or operation ....
