### ISSUE TITLE
I am unable to succesfully intall BlendOs

### ISSUE THREAD

**Issue by samcon30** [blend-os/blendOS#63]
as the title suggests I am unable to install it I can provide the jade log but it lacks some info in the actual install it said /mnt is not something I cant remember exactly but it gets stuck at 1% and then says its done but fails to boot from request ssd because of course it stopped at 1% https://docs.google.com/document/d/1BSGmYW1DHSdHW3CyPySd4EoPQTRur1rz_IhvA57oOwM/edit?usp=sharing

**Comment by samcon30** [comment]
I have tried from two different USB drives the result is the same and I have re-flashed the iso on both multiple times sometimes it makes it to 12% but it hasn't finished so IDK what to do now but submit an issue and hope for help

**Comment by phanesoaks** [comment]
I get the exact same issue. Not sure how to fix it. Tried multiple things.

**Comment by Zohiu** [comment]
You should re-download the ISO. The issue has been fixed.

**Comment by Souldragon9912** [comment]
re-download the new iso file. if your using a ventoy drive like me, boot into grub 2. if not you will get a failed installation every time. trust me, i fought for 6 hours trying to install blend. with this os being as new as it is, best thing i can suggest is to wait out like i am. while they fix the bugs, and get it to a more stable version.

**Comment by phanesoaks** [comment]
Sweet yes it was fixed. I didn't think there was a hot fix because there were no notes and version didn't change. Case closed. Excellent job. Working well 👍

**Comment by samcon30** [comment]
Sorry been ahwile since I checked this. Gonna close it given others have said it was fixed. Decided not to use blendos on primary rig and just use stock Arch. Well I messed up something with the stock Arch now and don't feel like fixing it, so going back to the blendos.
