### ISSUE TITLE
Unable to install on HP laptop

### ISSUE THREAD

**Issue by c-leri** [blend-os/blendOS#65]
When I try to install blendOS v2.0 on my laptop using the installer be it in the gnome or the plasma iso, I get an error saying "/mnt isn't a mount point", the installation would end after that displaying "Successful installation" but I couldn't boot into the "successful" install.

I tried manually partinioning and mounting the disk for the install and it would fail a bit further in the process when trying to install grub, it doesn't really gives an error message at this point either but the installation abruptly stops and I rebooting sends me right back to the live iso.

I think I encountered similar issues trying to install blendOS into a gnome boxes VM but I didn't really document it since I could just switch to Virtualbox and it would work without an issue.

**Comment by phanesoaks** [comment]
I'm having the same issue on my desktop. It will say successful but it doesn't show in boot for selection.  I looked into it on different USB media, diff ports, diff UEIF/Legacy noting. On windows it shows that the usb drive did not get partitioned.

So , like you, I also tried manually partitioning the drive and no success.  Strange. Maybe I'll try and older version of blendOS to see if it works.

**Comment by RudraSwat** [comment]
This should be fixed in the latest ISO.

**Comment by c-leri** [comment]
It is, thanks !
