### ISSUE TITLE
Stack at "selecting locals" section.

### ISSUE THREAD

**Issue by navod01** [blend-os/blendOS#66]
I try so many times to install BlendOS , but always it's installer got stack at "selecting locals" section.

**Comment by wolfsolver** [comment]
Same issue. Only pass if no change is Made on previous screen (so left default value as region). Unfortunately even pass on locale screen cannot create user (remain always in red).
Both on virtualbox and Hyper-V

**Comment by yechielw** [comment]
It seams like you it fails if your location is set to outside of USA

**Comment by RudraSwat** [comment]
This should be fixed in the latest ISO.
