### ISSUE TITLE
can't boot up installer

### ISSUE THREAD

**Issue by yukendhiran** [blend-os/blendOS#7]
I  downloaded iso image this morning 
I tried to boot up in grub mode , it thrown an error kernal not found
I tried to boot up in normal mode , it just in the loading screen for long time

I tried with  ventoy and rufus to create bootable image and I tried it on lenovo e1-25

**Comment by Xmayer-72** [comment]
I'm having the same issues. Having no issues booting other live iso's

**Comment by Samia-47** [comment]
use etcher to make bootable USB
and it will solve the problem

**Comment by yukendhiran** [comment]
> 

did you installed it

**Comment by lisandrocarmona** [comment]
I can only boot the ISO via Etcher (Rufus and Ventoy failed to me).
After a longer time booting (comparing to any other ISO), I could configure Jade (installer) but it keeps there forever, without any of its processes using CPU.

Intel Graphics, KDE, BTRFS were chosen for the installation into Jade.

**Comment by pabloab** [comment]
@yukendhiran Could you reopen the issue? I'd the same issue using Ventoy. It seems a blendOS bug and (if so) should be fixed.
