### ISSUE TITLE
User partition

### ISSUE THREAD

**Issue by nk3z** [blend-os/blendOS#74]
I'm installing blendos with the manual partition and the boot and system are partitioned fine but Home can't select an existing partition, the two times I've tried Home ends up inside the system. I use this Home partition with other Arch and Fedora systems and there is no problem between them.

**Comment by Vybo** [comment]
I'm having a similar issue, the installer won't let me continue if I select manual partition for System and Boot, the button is not enabled.

**Comment by nk3z** [comment]
I have tried again with v3 and this time I have tried a clean manual installation, only reusing the boot but with a root and home in clean partitions and it still ignores creating a separate home partition.

**Comment by nk3z** [comment]
I installed it by burning the image with etcher instead of ventoy and it worked

**Comment by NathanielPrescott** [comment]
I am having the same issue where I cannot go next after a manual partition with multiple drives.
